// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5TP_qBs-nfNebsd5xEWN98NK93XYvXs4',
    appId: '1:234819653523:web:bfc80390e47bb2425c6266',
    messagingSenderId: '234819653523',
    projectId: 'gym-logger-2',
    authDomain: 'gym-logger-2.firebaseapp.com',
    storageBucket: 'gym-logger-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxUavsxSUqKcB2tgdrdHR52pPDzYU_JUk',
    appId: '1:234819653523:android:f1c44d290d26a0135c6266',
    messagingSenderId: '234819653523',
    projectId: 'gym-logger-2',
    storageBucket: 'gym-logger-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4bqtfQf-wNdApRTL9Zjr-o2puzfGinow',
    appId: '1:234819653523:ios:809166584da145cd5c6266',
    messagingSenderId: '234819653523',
    projectId: 'gym-logger-2',
    storageBucket: 'gym-logger-2.appspot.com',
    iosBundleId: 'com.example.gymLogger2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4bqtfQf-wNdApRTL9Zjr-o2puzfGinow',
    appId: '1:234819653523:ios:8e052c270456f0265c6266',
    messagingSenderId: '234819653523',
    projectId: 'gym-logger-2',
    storageBucket: 'gym-logger-2.appspot.com',
    iosBundleId: 'com.example.gymLogger2.RunnerTests',
  );
}
